name: Sync with Azure DevOps

on:
  schedule:
    - cron: '*/15 * * * *'
  issues:
    types: [opened, closed, deleted, reopened, edited, labeled, unlabeled, assigned, unassigned]
  issue_comment:
    types: [created]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Sync workflow
    steps:       
    - uses: actions/checkout@v3
    - uses: a11smiles/GitSync@main
      env:     
        ado_token: '3TRVCvZwWW6zV1X0qh10YwyTw5s0FpgPph2s9VnNklfPGEZefcewJQQJ99BEACAAAAAW807oAAASAZDO2Ecu'
        github_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
